paths:
  /user/login:
    post:
      tags:
        - User
      summary: 로그인 로직 처리
      parameters:
        - name: userIDPW
          in: body
          required: true
          schema:
            properties:
              id:
                type: string
              pw:
                type: string
      responses:
        '200':
          description: 로그인 성공
        '400':
          description: 입력 값 없음
        '404':
          description: 로그인 실패 (아이디, 비밀번호 불일치)
  /user/signin:
    post:
      tags:
        - User
      summary: 회원가입
      parameters:
      - name: signIn
        in: body
        required: true
        schema:
          properties:
            email:
              type: string
              description: 유저 이메일
              example: swaggerTest@mail.com
            name:
              type: string
              description: 유저 이름
              example: swagger
            gender:
              type: string
              description: 유저 성별
              example: M
            birthYear:
              type: integer
              description: 생일 년도
              example: 2000
            birthMonth:
              type: integer
              description: 생일 월
              example: 1
            birthDay:
              type: integer
              description: 생일 일
              example: 31
            addr:
              type: string
              description: 주소
              example: swagger Test address
            specAddr:
              type: string
              description: 상세 주소
              example: swagger Test specAddr
            phone:
              type: string
              description: 전화 번호
              example: 010-0000-0000
            prefer:
              type: array
              description: 선호 카테고리 번호
              example: [1, 3, 5]
      responses:
        '200':
          description: 회원 가입 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "email": "swaggerTest@mail.com",
                  "name": "swagger",
                  "preferCategory": [
                    "한식",
                    "일식"
                  ]
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

  /user/review:
    get:
      tags:
        - User
      summary: 자기가 작성한 리뷰 조회
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            properties:
              userId:
                type: integer
                example: 1
        - name: reviewId
          in: query
          required: false
          schema:
            properties:
              reviewId:
                type: integer
                example: 1
        - name: paging
          in: query
          required: false
          schema:
            properties:
              size:
                type: integer
                example: 1
      responses:
        '200':
          description: 리뷰 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "reviewId": 1,
                  "userId": 1,
                  "userName": "user",
                  "rate": 4.5,
                  "context": "Review Context",
                  "created_at": "2000-00-00"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

  /user/missions:
    get:
      tags:
        - User
      summary: 자신이 진행 혹은 완료한 미션 조회
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            properties:
              userId:
                type: integer
                example: 1
        - name: missionId
          in: query
          required: false
          schema:
            properties:
              reviewId:
                type: integer
                example: 1
        - name: paging
          in: query
          required: false
          schema:
            properties:
              size:
                type: integer
                example: 1
        - name: status
          in: query
          required: true
          schema:
            properties:
              size:
                type: string
                example: "active"
      responses:
        '200':
          description: 사용자 미션 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "userMissionId": 1,
                  "missionId": 1,
                  "status": "active",
                  "context": "Mission Context",
                  "deadline": "2000-00-00",
                  "point": 500,
                  "created_at": "2000-00-00"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

  /user/mission:
    patch:
      tags:
        - User
      summary: 자신의 진행 미션 성공으로 바꾸기
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            properties:
              userId:
                type: integer
                example: 1
        - name: missionId
          in: query
          required: true
          schema:
            properties:
              reviewId:
                type: integer
                example: 1
        - name: paging
          in: query
          required: false
          schema:
            properties:
              size:
                type: integer
                example: 1
      responses:
        '200':
          description: 성공으로 상태 변화 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: [{
                  "userMissionId": 1,
                  "missionId": 1,
                  "status": "success",
                  "context": "Mission Context",
                  "created_at": "2000-00-00"
                  }, {
                  "userMissionId": 1,
                  "missionId": 1,
                  "status": "success",
                  "context": "Mission Context",
                  "created_at": "2000-00-00"
                  }]
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.